# Generated by Django 2.2.5 on 2019-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('power', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_of_applicance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hours_used_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amp_rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('volt_rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
