# Generated by Django 2.2.5 on 2019-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.CharField(max_length=400)),
                ('watt_per_hour', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=12, null=True)),
                ('quantity_of_appliance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hours_used_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('appliance',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
