# Generated by Django 2.2.5 on 2019-09-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliances',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='appliances',
            old_name='quantity_of_applicance',
            new_name='quantity_of_appliance',
        ),
    ]
