# Generated by Django 2.2.5 on 2019-09-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_auto_20190924_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='amp_rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='volt_rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=12, null=True),
        ),
    ]
