# Generated by Django 2.2.5 on 2019-09-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_auto_20190924_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliances',
            options={'ordering': ('appliance',)},
        ),
        migrations.RenameField(
            model_name='appliances',
            old_name='name',
            new_name='appliance',
        ),
        migrations.RenameField(
            model_name='appliances',
            old_name='amp_rating',
            new_name='watt_per_hour',
        ),
        migrations.RemoveField(
            model_name='appliances',
            name='power',
        ),
        migrations.RemoveField(
            model_name='appliances',
            name='volt_rating',
        ),
    ]
